<?=
$this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('banner-main')
    ->toHtml();

?>
<script>
    require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
        $('.main-banner').slick({
       dots: false,
       infinite: true,
       speed: 300,
       arrows: false,
       slidesToShow: 1,
       slidesToScroll: 1
    });

    });
});

</script>