
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('you_may_also_like')
        ->toHtml();
    ?>
<script>
    require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
        $('.widget-product-grid').slick({
       dots: false,
       infinite: true,
       speed: 300,
       arrows: false,
       slidesToShow: 4,
       slidesToScroll: 3
    });
    });
});
</script>